language: "perl"
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"

before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y libgmp-dev

install:
    - cpanm --installdeps . 


script:
    - perl annotate_parser.pl -i ./test/output_annotate.txt -o converted_annotation.txt

notification:
    email: false
